#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          avito:
#            authorization-grant-type: jwt-bearer
#            client-id: CtQF68Zjm3Sr_4wyUsKv
#            client-secret: yms1O5Ox5o7TBsKnPmXOpajKbbiEuKtq0UvJEgn8
#        provider:
#          avito:
#            token-uri: https://api.avito.ru/token
#            user-info-authentication-method: header